### PR TITLE
Add some timer outputs.

### PR DESCRIPTION
**Pull request by maleadt**
https://github.com/JuliaGPU/CUDAnative.jl/issues/354

```
[ Info: Testing using device GeForce GTX TITAN
────────────────────────────────────────────────────────
                                          Time          
                                  ──────────────────────
        Tot / % measured:               109s / 11.6%    

Section                   ncalls     time   %tot     avg
────────────────────────────────────────────────────────
LLVM IR generation           250    5.95s  47.3%  23.8ms
Julia IR generation          256    2.90s  23.1%  11.3ms
CUDA object generation       170    2.52s  20.0%  14.8ms
PTX assembly generation      210    1.20s  9.57%  5.72ms
────────────────────────────────────────────────────────
Test Summary: | Pass  Total
CUDAnative    |  279    279
```

Seems reasonable.

### CODE REVIEW

**Comment by vchuravy** [comment]
@lcw @ali-ramadhan, this might be helpful for you to understand the compilation costs of CLIMA

**Comment by maleadt** [comment]
Note that this branch builds on https://github.com/JuliaGPU/CUDAnative.jl/pull/362 which requires https://github.com/JuliaLang/julia/pull/31428.
After adding some more detailed timers:

```
 ──────────────────────────────────────────────────────────
                                             Time          
                                     ──────────────────────
          Tot / % measured:                106s / 11.0%    

 Section                     ncalls     time   %tot     avg
 ──────────────────────────────────────────────────────────
 LLVM middle-end                290    6.16s  52.4%  21.2ms
   IR generation                290    4.71s  40.1%  16.2ms
   optimization                 284    1.32s  11.2%  4.65ms
   device library               249   54.0ms  0.46%   217μs
   runtime library              249   42.2ms  0.36%   169μs
   verification                 289   8.20ms  0.07%  28.4μs
   strip debug info              65    212μs  0.00%  3.26μs
 Julia front-end                296    2.53s  21.6%  8.55ms
 CUDA object generation         170    1.83s  15.6%  10.8ms
   linking                      170    1.38s  11.7%  8.11ms
   compilation                  170    455ms  3.87%  2.67ms
 LLVM back-end                  210    1.22s  10.4%  5.80ms
   machine-code generation      207    307ms  2.62%  1.48ms
   preparation                  210   70.6ms  0.60%   336μs
 ──────────────────────────────────────────────────────────
```

**Comment by ali-ramadhan** [comment]
This looks awesome! Can't wait to try it out!

**Comment by maleadt** [comment]
@ali-ramadhan you should be able to test this on Julia 1.0/1.1/master now.

**Comment by ali-ramadhan** [comment]
Thanks for the heads up! Should help a lot with https://github.com/climate-machine/Oceananigans.jl/issues/66

Will update packages and give it a try.

**Pull request merged**
