### PR TITLE
Use new non-recursive codegen

### PR DESCRIPTION
**Pull request by maleadt**
Needs https://github.com/JuliaLang/julia/pull/25984, with additional changes from https://github.com/JuliaLang/julia/compare/jn/codegen-norecursion...tb/codegen-norecursion

### CODE REVIEW

**Comment by tshort** [comment]
Is the non-recursive codegen still going to happen prior to 0.7/1.0?

**Comment by maleadt** [comment]
Probably not. The scope of the upstream issue is much broader, and AFAIK Jameson isn't happy with the design yet.

**Comment by maleadt** [comment]
Updated for https://github.com/JuliaLang/julia/pull/25984/commits/2cd11c4a860465254e74c0c8b98628d4b3deec06; works pretty well but need to figure out how to deal with LLVM's contexts. There's an accessor (`jl_get_llvm_context`) but we can't use that during generated function -> llvmcall expansion because that happens before aotcompile.

**Comment by maleadt** [comment]
Looks like the new codegen broak float16 multiplication:

```
julia> CUDAnative.code_llvm(*, Tuple{Float16, Float16}; strict=true)
ERROR: InvalidIRError: compiling *(Float16, Float16) resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to jfptr_Float32_2275)

;  @ float.jl:398 within `*'
define dso_local i16 @_Z10julia_MUL_7Float167Float16(i16, i16) local_unnamed_addr {
top:
  %2 = call fastcc float @j_Float32_4187(i16 %0)
  %3 = call fastcc float @j_Float32_4188(i16 %1)


define internal fastcc float @j_Float32_4127(i16) unnamed_addr #0 {
top:
  %1 = alloca %jl_value_t addrspace(10)*, align 8
  %2 = call fastcc %jl_value_t addrspace(10)* @ptx_gc_pool_alloc(i64 2)
  %3 = bitcast %jl_value_t addrspace(10)* %2 to i16 addrspace(10)*
  store i16 %0, i16 addrspace(10)* %3, align 8
  store %jl_value_t addrspace(10)* %2, %jl_value_t addrspace(10)** %1, align 8
  %4 = call fastcc nonnull %jl_value_t addrspace(10)* @tojlinvoke4128(%jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 139691536025776 to %jl_value_t*) to %jl_value_t addrspace(10)*), %jl_value_t addrspace(10)** nonnull %1, i32 1)


define internal fastcc %jl_value_t addrspace(10)* @tojlinvoke4128(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) unnamed_addr {
top:
  %3 = call %jl_value_t addrspace(10)* @jfptr_Float32_2275(%jl_value_t addrspace(10)* %0, %jl_value_t addrspace(10)** %1, i32 %2, %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 139690687678928 to %jl_value_t*) to %jl_value_t addrspace(10)*))
  ret %jl_value_t addrspace(10)* %3
}
```


Whereas on 1.3:

```julia
;  @ float.jl:398 within `*'
define i16 @julia___29(i16, i16) {
top:
  %2 = call float @julia_Float32_17988(i16 %0)
  %3 = call float @julia_Float32_17988(i16 %1)

;  @ float.jl:209 within `Float32'
define internal float @julia_Float32_17988(i16) {
top:
; normal code
```
```

**Pull request merged**
