### PR TITLE
pow function for exponet is Int64

### PR DESCRIPTION
**Pull request by chengchingwen**
ref: https://github.com/JuliaGPU/CuArrays.jl/pull/325

### CODE REVIEW

**Comment by chengchingwen** [comment]
@vchuravy Let's all right :)
I'm not familiar with testing CUDAnative, and I didn't find the test for the `CUDAnative.pow` in the test folder. Could tell me what/how should I do?

**Comment by vchuravy** [comment]
I think this is the right place https://github.com/JuliaGPU/CUDAnative.jl/blob/59166089cda2fc579023b2865fdb7b59fc983f0e/test/device/cuda.jl#L33

**Comment by chengchingwen** [comment]
I add a few test for the `pow` function. Is these ok?

**Comment by vchuravy** [comment]
bors try

**Comment by maleadt** [comment]
Thanks, great contribution! Though I've been purposefully not adding such extra methods, since I had hoped to keep these wrappers low-level and integrate them with eg. `Base.^` as soon as we have Cassette. But it can't hurt to add a couple for convenience, since Cassette seems to take a while.

**Pull request merged**
