### PR TITLE
Add some more complex operations

### PR DESCRIPTION
**Pull request by benchislett**
#430 

This may not be the way we want to do this, and I'm open to alternatives, but as I see it this is an effective solution.

If we want a more full set of operations to match those for real values, I can add those as well--just not sure how far we want to go.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Is there any reason why this is not being considered for merging? 
I would find It very useful.

On a related note, it might be useful to also add `log1p` to the list.

**Comment by maleadt** [comment]
> Is there any reason why this is not being considered for merging?
> I would find It very useful.

Sorry, I forgot about this PR. Could you add some tests?

**Comment by PhilipVinc** [comment]
@benchislett if you don't have time to do it I can take care of the tests.
I'd love this to be merged relatively soon.

**Comment by PhilipVinc** [comment]
@benchislett as you did not answer I took the liberty of taking your commit and adding tests
PR #445.

If you prefer to handle this yourself, just tell me and I can close the PR.

**Pull request merged**
