### PR TITLE
skip verifier if requested

### PR DESCRIPTION
**Pull request by vchuravy**
bors try

### CODE REVIEW

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
I intentionally didn't add `__do_not_verify` into CUDAnative proper since I hope the we do not need it in the long run (also the reason why I am only matching the name).
It very much depends if we want #334 later or earlier. I have been working on this functionality for GPUifyLoops.jl and I am ironing out the kinks over there.

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
@maleadt Ok to merge?

**Comment by maleadt** [comment]
Looks good!

**Pull request merged**
