### PR TITLE
prototype nvvm.annotations for `__launch_bounds__`

### PR DESCRIPTION
**Pull request by vchuravy**
I was trying to setup something similar to CUDA-C `__launch_bounds__`
mimicking how Clang does it, but I don't think the annotation is properly passed.

Any pointer/ideas how to correctly do this?

### CODE REVIEW

**Comment by maleadt** [comment]
like this?
https://github.com/JuliaGPU/CUDAnative.jl/blob/d18eca306f48ccd7b0cf05cd090bbd6880e32b11/src/jit.jl#L374-L378

But we really don't now the min/max CTA size, so where do you want to get this info from?

**Comment by maleadt** [comment]
Also, if we were to propagate the launch configuration to the CUDAnative compiler, we could just as well generate new LLVM IR with range metadata attached to the launch bounds intrinsics. That way, we let LLVM optimize the IR given knowledge about the launch bounds, which I presume to be more effective then only letting the PTX JIT optimize with that knowledge.

**Comment by vchuravy** [comment]
Ha I thought I grep'd the repo for `nvvm`, silly me.

Does LLVM actually use that information? But yes that would sound like the best solution.

**Comment by maleadt** [comment]
Yes, https://reviews.llvm.org/rL211281

**Comment by maleadt** [comment]
Oh, I see where you're coming from: you want to influence the PTX JIT's register allocator (as per the hint in nvvp)?

**Comment by vchuravy** [comment]
Yeah that was what I was trying to do, much less relevant now for the problem. 
I wanted to set either `--maxrregcount` or `__launch_bounds__` to allow PTXAS to optimise register usage for the know number of threads.

**Pull request closed without merging**
