### PR TITLE
add threadfence intrinsics

### PR DESCRIPTION
**Pull request by vchuravy**
The documentation is mostly verbatim from the CUDA handbook.

cc: @lcw

### CODE REVIEW

**Comment by maleadt** [comment]
:+1:
Exports and tests?

**Comment by maleadt** [comment]
`nanosleep` might also be useful

```julia
if cuda_driver_version >= v"10.0" && v"6.2" in ptx_support
    export nanosleep

    function nanosleep(t::Unsigned)
        @asmcall("nanosleep.u32 \$0;", "r", true,
                 Cvoid, Tuple{UInt32}, convert(UInt32, t))
    end
end
```

**Comment by vchuravy** [comment]
bors try

**Comment by maleadt** [comment]
LGTM. Maybe add a similar note to `nanosleep`? Go ahead and `bors r+` when you want.

**Comment by vchuravy** [comment]
bors r+ 

Already hat the note for nanosleep :)

**Pull request merged**
