### PR TITLE
Add verbose option to code_sass

### PR DESCRIPTION
**Pull request by thomasfaingnaert**
This PR adds a `verbose` option to `@device_code_sass` and friends, which prints code generation statistics such as number of used registers, used constant memory, register spilling, ...

Example:
```julia
julia> function kernel()
           return
       end
kernel (generic function with 1 method)

julia> @device_code_sass @cuda kernel()
	.headerflags	@"EF_CUDA_TEXMODE_UNIFIED EF_CUDA_64BIT_ADDRESS EF_CUDA_SM75 EF_CUDA_VIRTUAL_SM(EF_CUDA_SM75)"
	.elftype	@"ET_EXEC"


//--------------------- .text.ptxcall_kernel_2    --------------------------
	.section	.text.ptxcall_kernel_2,"ax",@progbits
	.sectioninfo	@"SHI_REGISTERS=4"
	.align	128
        .global         ptxcall_kernel_2
        .type           ptxcall_kernel_2,@function
        .size           ptxcall_kernel_2,(.L_12 - ptxcall_kernel_2)
        .other          ptxcall_kernel_2,@"STO_CUDA_ENTRY STV_DEFAULT"
ptxcall_kernel_2:

.text.ptxcall_kernel_2:
        MOV R1, c[0x0][0x28] ;
        EXIT ;

.L_1:
        BRA `(.L_1);

.L_12:

julia> @device_code_sass verbose=true @cuda kernel()
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'ptxcall_kernel_3' for 'sm_75'
ptxas info    : Function properties for ptxcall_kernel_3
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 4 registers, 352 bytes cmem[0]
	.headerflags	@"EF_CUDA_TEXMODE_UNIFIED EF_CUDA_64BIT_ADDRESS EF_CUDA_SM75 EF_CUDA_VIRTUAL_SM(EF_CUDA_SM75)"
	.elftype	@"ET_EXEC"


//--------------------- .text.ptxcall_kernel_3    --------------------------
	.section	.text.ptxcall_kernel_3,"ax",@progbits
	.sectioninfo	@"SHI_REGISTERS=4"
	.align	128
        .global         ptxcall_kernel_3
        .type           ptxcall_kernel_3,@function
        .size           ptxcall_kernel_3,(.L_12 - ptxcall_kernel_3)
        .other          ptxcall_kernel_3,@"STO_CUDA_ENTRY STV_DEFAULT"
ptxcall_kernel_3:

.text.ptxcall_kernel_3:
        MOV R1, c[0x0][0x28] ;
        EXIT ;

.L_1:
        BRA `(.L_1);

.L_12:
```

### CODE REVIEW

**Comment by maleadt** [comment]
Sounds good!
bors r+

**Comment by thomasfaingnaert** [comment]
@maleadt Seems CI is broken:
```
ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=10.2\\\\n\\\"\"": unknown (executor_docker.go:834:5s)
```

**Comment by maleadt** [comment]
the `nvidia/cuda:latest` Docker tag has been bumped to 10.2, which the NVIDIA driver on cyclops does not provide. I'll change it on master, you can rebase afterwards.

**Comment by thomasfaingnaert** [comment]
@maleadt Rebased.

**Comment by maleadt** [comment]
bors d+
bors r+

**Pull request merged**
