### PR TITLE
add abs for complex

### PR DESCRIPTION
**Pull request by Roger-luo**
I'm not sure if this is the right place to add it. But I think this is not there in the kernel.

### CODE REVIEW

**Comment by vchuravy** [comment]
I don't think we want to reimplement the entire Complex interface in CUDAnative. In the long-run we will pursue the Cassette based approach in #334 (Julia 1.3). In the short-term you can use `GPUifyLoops.contextualize`

**Comment by Roger-luo** [comment]
I see. Is there any doc for this? Or if I use `@loop` macro it will add the context automatically?

**Comment by vchuravy** [comment]
https://github.com/vchuravy/GPUifyLoops.jl/blob/master/examples/contextualize.jl

**Comment by Roger-luo** [comment]
@vchuravy I didn't get it, there's no call to this function `contextualize` in the example. Do you mean I could also just use `@launch CUDA()`? and it will overdub a context to my source code?

**Comment by vchuravy** [comment]
Ah right, sorry about that. Yes you could just use `@launch CUDA()` or see here for a example https://github.com/vchuravy/GPUifyLoops.jl/blob/760700e12f88c4bebb072d5f0453bed1d24692a3/test/test.jl#L53-L57

**Comment by Roger-luo** [comment]
Ah I see thanks.

**Pull request closed without merging**
