### PR TITLE
Use LLVM for inline assembly

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@vchuravy maybe we should put this, and cgutils, in LLVM.jl.

**Comment by vchuravy** [comment]
I was thinking about if LLVM.jl is appropriate. But probably we can just have a submodule tools that can be used if you need it. The usage of jlctx is probably the only problem

**Comment by maleadt** [comment]
Maybe an `LLVM.Interop` submodule where usage of the Julia LLVM context is implied module-wide.

**Comment by maleadt** [comment]
ref https://github.com/maleadt/LLVM.jl/pull/65

**Pull request merged**
