### PR TITLE
examples for nvcxx

### PR DESCRIPTION
**Pull request by vchuravy**
All this is in prototypical stage and need better integration.

`saxpy.jl` is functional and `curand.jl` still needs a bit of work.

### CODE REVIEW

**Comment by vchuravy** [comment]
The examples require LLVM 3.8 and the current master of Cxx.jl

**Comment by vchuravy** [comment]
I extended the examples to contain the calls to CUDAdrv and CUDAnative

**Comment by vchuravy** [comment]
Updated the curand demo. Needs #3.

**Comment by maleadt** [comment]
I wouldn't close this, it contains the necessary boilerplate for setting-up Cxx and it's definitely where we want to end up, it's just that for now it's impossible to make this perform well (lacking some "pointer to otherwise non-escaping stack object" primitive)...

**Comment by vchuravy** [comment]
I closed this because all of this machinery now lives in https://github.com/JuliaGPU/CUDAnativelib.jl, but we can keep this since it is a more minimal example.

**Pull request closed without merging**
