### PR TITLE
nvdisasm doesn't reliably work on CUDA >= 9.1 for LLVM 6.0.1

### LINKED ISSUE #396: `nvdisasm` needs version CUDA 9.0 use cuobjdump instead if newer

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #396

### CODE REVIEW

**Comment by maleadt** [comment]
Can you elaborate? I've been successfully (AFAIK) using `nvdisasm`/`code_sass` on CUDA 10.1...

**Comment by vchuravy** [comment]
One the kernels in #398 @lcw observed:

```
vchuravy@cyclops ~/H/e/volumerhs-small> ~/julia/julia --project=. volumerhs.jl 
[ Info: Building the CUDAnative run-time library for your sm_70 device, this might take a while...
nvdisasm error   : Untrackable indirect branch (needs a SIBCALL annotation?)
nvdisasm error   : Untrackable indirect branch (needs a SIBCALL annotation?)
nvdisasm error   : Untrackable indirect branch (needs a SIBCALL annotation?)
nvdisasm error   : Untrackable indirect branch (needs a SIBCALL annotation?)
nvdisasm error   : Untrackable indirect branch (needs a SIBCALL annotation?)
ERROR: Error while loading expression starting at /home/vchuravy/Heptapus.jl/examples/volumerhs-small/volumerhs.jl:243
caused by [exception 1]
failed process: Process(`/usr/bin/nvdisasm --print-code --print-line-info /tmp/jl_BP6M9o`, ProcessExited(1)) [1]
```
If `ptxas` from 9.0 is disassembly is successful and Clang 6.0.1 only support 9.0
I hadn't had a chance to test with CUDA 10

**Comment by maleadt** [comment]
> If `ptxas` from 9.0 is disassembly is successful and Clang 6.0.1 only support 9.0

I can't parse that...

Could it be that you're using a CUDA toolkit (from which we pick up `nvdisasm`) with a CUDA version that is below the CUDA version as reported by the driver? Because, and this is just a guess, `nvdisasm` is 22MB so it might include a copy of the compiler and its disassembler while `cuobjdump` is only 182K and looks like it might be reusing the compiler infrastructure as part of `libcuda` (both don't dynamically link against any CUDA library).

**Comment by maleadt** [comment]
Good to go?

**Comment by maleadt** [comment]
So it looks like `cuobjdump` just uses `nvdisasm`:

```
shell> cuobjdump --dump-sass /tmp/test.cubin

        code for sm_75
                Function : ptxcall_identity_4
nvdisasm fatal   : Value 'SM75' is not defined for option 'binary'
```

**Comment by maleadt** [comment]
We're now dumping the CUBIN as generated by the CUDA driver, so the behavior of this might have changed. Furthermore, CUPTI documents that we should use nvdisasm. There's possibility for a mismatch though, if you're using a CUDA toolkit that's much older than the CUDA capabilities of your driver. Either way, I don't think we should switch to cuobjdump right now (esp. since we can't ship either nvdisasm or cuobjdump when switching to BB, so I'd rather only use one of those).

**Pull request closed without merging**
