### PR TITLE
WIP: Introduce at-narrow to narrow literals in expressions.

### PR DESCRIPTION
**Pull request by maleadt**
May need an NSFW tag.

Ref #25

### CODE REVIEW

**Comment by maleadt** [comment]
Hmm.
```julia
julia> dump(@narrow 1000÷-2)
UInt16 65036

julia> dump(1000÷-2)
Int64 -500
```

**Comment by maleadt** [comment]
wat
```julia
julia> dump(UInt16(1000)÷-2)
UInt64 18446744073709551116

julia> dump(UInt16(1000)÷-UInt64(2))
UInt64 0

julia> dump(UInt16(1000)÷-UInt32(2))
UInt32 0

julia> dump(UInt16(1000)÷-UInt16(2))
UInt16 0

julia> dump(UInt16(1000)÷-UInt8(2))
UInt16 3
```

OK maybe I shouldn't be doing this.

**Comment by maleadt** [comment]
Hmm, unsigned behaviour doesn't seem all that reliable, let alone at different bit widths:
````
julia> dump(UInt8(255)+1)
Int64 256

julia> dump(UInt16(255)+1)
Int64 256

julia> dump(UInt32(255)+1)
Int64 256

julia> dump(UInt64(255)+1)
UInt64 256
```

Maybe I should just specialize `narrow` to make literals 32-bit and converts to Int/UInt without width use 32-bit variants.

**Comment by SimonDanisch** [comment]
I wonder how helpful this is! The main reason why I personally would like to have better behaviour is, to make it easier to work with user defined function that don't even know of this problem. If they don't know of the problem, they obviously won't use a narrow macro... And people who know of this, can easily sprinkle UInt32(x) around, no?
Or am I misinterpreting the purpose of this PR?

**Comment by maleadt** [comment]
> And people who know of this, can easily sprinkle UInt32(x) around, no?

You're right, I mostly intended it to be a quick hack to keep code readable (while porting Rodinia benchmarks). If it turns out to be reliable and doesn't break too much code, we could however consider using it as part of `@cuda`. But #25 definitely needs some more thought than just this band-aid.

**Comment by maleadt** [comment]
https://github.com/stevengj/ChangePrecision.jl

**Pull request closed without merging**
