### PR TITLE
Grid Synchronization with Cooperative Groups

### PR DESCRIPTION
**Pull request by qin-yu**
Introduced two functions `this_grid()` and `sync_grid()` to implement synchronisation of all blocks within a grid. One can now pass a keyword arguement `cg::Bool=false` to `@cuda` and launch cooperative kernel (implemented in CUDAdrv, see [my other pull request](https://github.com/JuliaGPU/CUDAdrv.jl/pull/134) in JuliaGPU/CUDAdrv.jl)

### CODE REVIEW

**Comment by vchuravy** [comment]
bors try

**Comment by qin-yu** [comment]
> ## try
> # Build failed
> * [ci/gitlab/trying](https://gitlab.com/JuliaGPU/CUDAnative.jl/pipelines/54858477)

I think one needs to build my PR in CUDAdrv first, then run test with that.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
oops.
bors r+

**Comment by maleadt** [comment]
Great! Thanks again, @qin-yu :slightly_smiling_face:

**Comment by qin-yu** [comment]
> Great! Thanks again, @qin-yu

Thanks again! Without encouragement, (plenty of) help and (perhaps?) [this PR](https://github.com/JuliaGPU/CUDAnative.jl/pull/356) from @vchuravy :droplet: and @maleadt :sunny:, I would not have made any contribution :seedling:

**Pull request merged**
