### PR TITLE
Use kernel wrapper functions to improve argument passing

### PR DESCRIPTION
**Pull request by maleadt**
Alternative to parametrizing the calling convention through eg. `CodegenParams`, idea from @vtjnash.

Depends on new version of LLVM.jl for maleadt/LLVM.jl#36

### CODE REVIEW

**Comment by maleadt** [comment]
Old:

```llvm
define void @julia_kernel_vadd(%CuDeviceArray.0* nocapture readonly dereferenceable(16), %CuDeviceArray.0* nocapture readonly dereferenceable(16), %CuDeviceArray.0* nocapture readonly dereferenceable(16)) local_unnamed_addr #0 !dbg !5 {
top:
  %3 = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x(), !dbg !7
  %4 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x(), !dbg !13
  %5 = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x(), !dbg !15
  %6 = add i32 %3, 1, !dbg !12
  %7 = zext i32 %6 to i64, !dbg !12
  %8 = add nsw i64 %7, -1, !dbg !12
  %9 = zext i32 %4 to i64, !dbg !12
  %10 = mul i64 %8, %9, !dbg !12
  %11 = add i32 %5, 1, !dbg !12
  %12 = zext i32 %11 to i64, !dbg !12
  %13 = getelementptr inbounds %CuDeviceArray.0, %CuDeviceArray.0* %0, i64 0, i32 1, !dbg !19
  %14 = add nsw i64 %12, -1, !dbg !12
  %15 = add i64 %14, %10, !dbg !19
  %16 = load float*, float** %13, align 8, !dbg !19, !tbaa !20
  %17 = getelementptr float, float* %16, i64 %15, !dbg !19
  %18 = load float, float* %17, align 8, !dbg !19, !tbaa !23
  %19 = getelementptr inbounds %CuDeviceArray.0, %CuDeviceArray.0* %1, i64 0, i32 1, !dbg !19
  %20 = load float*, float** %19, align 8, !dbg !19, !tbaa !20
  %21 = getelementptr float, float* %20, i64 %15, !dbg !19
  %22 = load float, float* %21, align 8, !dbg !19, !tbaa !23
  %23 = fadd float %18, %22, !dbg !19
  %24 = getelementptr inbounds %CuDeviceArray.0, %CuDeviceArray.0* %2, i64 0, i32 1, !dbg !19
  %25 = load float*, float** %24, align 8, !dbg !19, !tbaa !20
  %26 = getelementptr float, float* %25, i64 %15, !dbg !19
  store float %23, float* %26, align 8, !dbg !19, !tbaa !23
; Source line: 8
  ret void, !dbg !25
}
```

New:
```llvm
define void @ptxcall_kernel_vadd(%CuDeviceArray.0, %CuDeviceArray.0, %CuDeviceArray.0) local_unnamed_addr #1 {
entry:
  %.elt2 = extractvalue %CuDeviceArray.0 %0, 1
  %.elt5 = extractvalue %CuDeviceArray.0 %1, 1
  %.elt8 = extractvalue %CuDeviceArray.0 %2, 1
  %3 = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x(), !dbg !5
  %4 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x(), !dbg !13
  %5 = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x(), !dbg !15
  %6 = add i32 %3, 1, !dbg !11
  %7 = zext i32 %6 to i64, !dbg !11
  %8 = add nsw i64 %7, -1, !dbg !11
  %9 = zext i32 %4 to i64, !dbg !11
  %10 = mul i64 %8, %9, !dbg !11
  %11 = add i32 %5, 1, !dbg !11
  %12 = zext i32 %11 to i64, !dbg !11
  %13 = add nsw i64 %12, -1, !dbg !11
  %14 = add i64 %13, %10, !dbg !19
  %15 = getelementptr float, float* %.elt2, i64 %14, !dbg !19
  %16 = load float, float* %15, align 8, !dbg !19, !tbaa !20
  %17 = getelementptr float, float* %.elt5, i64 %14, !dbg !19
  %18 = load float, float* %17, align 8, !dbg !19, !tbaa !20
  %19 = fadd float %16, %18, !dbg !19
  %20 = getelementptr float, float* %.elt8, i64 %14, !dbg !19
  store float %19, float* %20, align 8, !dbg !19, !tbaa !20
  ret void
}
```

Should be significantly faster because of not accessing global memory, but using (SMX-local) parameter space instead.

**Comment by maleadt** [comment]
Passes tests, yay! TODO: tag LLVM.jl, rip out old allocation code.

**Comment by Evizero** [comment]
Is the intention that the `pointer(myarray)` workaround is no longer needed?

I tried applying it to my use case but I get a serious regression. The change I made looks like the following

```diff
diff --git a/src/backends/cuda.jl b/src/backends/cuda.jl
index 23d9f11..7d454a3 100644
--- a/src/backends/cuda.jl
+++ b/src/backends/cuda.jl
@@ -77,22 +77,18 @@ function update!(state::BoxState{3,T}, backend::CUDABackend, sim) where T
     zblocks = ceil(Int, v / threads[3])
     #shmem = Int(2 * prod(threads.+2) * sizeof(T))
     @cuda ((xblocks,yblocks,zblocks),threads) cuda_kernel!(
-        pointer(state.previous), pointer(state.current),
-        pointer(state.q),
-        h, w, v,
+        state.previous, state.current, state.q,
         sim.wave.λ,
         state.box.γ)
     state
 end
 
-function cuda_kernel!(previous_ptr::Ptr{T}, current_ptr::Ptr{T}, q_ptr::Ptr, h::Int, w::Int, v::Int, λ::T, γ::T) where T
+function cuda_kernel!(Ψt₋₁::CuDeviceArray{T}, Ψt::CuDeviceArray{T}, q::CuDeviceArray, λ::T, γ::T) where T
     y = (blockIdx().y-1) * blockDim().y + threadIdx().y
     x = (blockIdx().x-1) * blockDim().x + threadIdx().x
     z = (blockIdx().z-1) * blockDim().z + threadIdx().z
-    Ψt₋₁ = CuDeviceArray((h,w,v), previous_ptr)
-    Ψt   = CuDeviceArray((h,w,v), current_ptr)
-    Ψt₊₁ = CuDeviceArray((h,w,v), previous_ptr)
-    q    = CuDeviceArray((h,w,v), q_ptr)
+    h, w, v = size(Ψt₋₁)
+    Ψt₊₁ = Ψt₋₁
     eins = one(T)
     zwei = eins + eins
     λsq = λ*λ
```

```
TrialJudgement(+11209.18% => regression)
```

its 19 ms instead of 170 us when using the `pointer(...)` approach. (as a side note it is still beating 12 core multithreaded version by a factor of 2 though)

Might be that I misunderstood this PR or made a wrong change (the results look correct though). Just to be clear I am not complaining here. This is not an issue for me. I am just sharing my observation

**Comment by Evizero** [comment]
oh, wait, wait I might be an idiot and am on the wrong CUDAnative commit

**Comment by Evizero** [comment]
Yes, I forgot to checkout master

Now I get the following, which might be a spurious regression (I am still tweaking around with my benchmark partameters)

```
 TrialJudgement(+5.40% => regression)
```

That is a much smaller number than `11209.18%` 🎉

**Comment by maleadt** [comment]
Great! Yeah the `pointer` workaround should never be necessary anymore. Any regression is a bug though, so if you can demonstrate this being an issue, please file a bug.

**Pull request merged**
