### PR TITLE
Fix cuprintf tests on win64.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Fixes #190

**Comment by SimonDanisch** [comment]
```
julia>

(v0.7) pkg> test CUDAnative
   Testing CUDAnative
 Resolving package versions...
  Updating `C:\Users\sdani\juliastuff\cygwin\tmp\jl_941.tmp\Project.toml`
  [3895d2a7] + CUDAapi v0.4.3
  [e30172f5] + Documenter v0.18.0
  [7a1cc6ca] - FFTW v0.2.2
  [0c68f7d7] - GPUArrays v0.2.4+ [`C:\Users\sdani\.julia\dev\GPUArrays`]
  [295af30f] - Revise v0.3.0
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [44cfe95a] + Pkg
  [9a3f8284] - Random
  [8dfed614] + Test
  Updating `C:\Users\sdani\juliastuff\cygwin\tmp\jl_941.tmp\Manifest.toml`
  [621f4979] - AbstractFFTs v0.3.1
  [9e28174c] - BinDeps v0.8.8
  [864edb3b] - DataStructures v0.8.3
  [ffbed154] + DocStringExtensions v0.4.4
  [e30172f5] + Documenter v0.18.0
  [7a1cc6ca] - FFTW v0.2.2
  [0c68f7d7] - GPUArrays v0.2.4+ [`C:\Users\sdani\.julia\dev\GPUArrays`]
  [189a3867] - Reexport v0.1.0
  [295af30f] - Revise v0.3.0
  [90137ffa] - StaticArrays v0.7.0
  [30578b45] - URIParser v0.3.1
  [7b1f6079] - FileWatching
  [ea8e919c] - SHA
delayed lookup: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:214
  Expression: err isa CUDAnative.CompilerError
   Evaluated: UndefVarError(:LLVMGetSourceLocation) isa CUDAnative.CompilerError
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:214 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:210 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
delayed lookup: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:216
  Expression: occursin("could not compile codegen_ref_nonexisting() for GPU; unsupported LLVM IR", msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:216 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:210 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
delayed lookup: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:217
  Expression: occursin("Reason: unsupported call to the Julia runtime", msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:217 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:210 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
delayed lookup: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:218
  Expression: occursin(#= C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:218 =# @r_str("\\[1\\] codegen_ref_nonexisting at .*codegen.jl"), msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:218 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:210 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
generic call: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:227
  Expression: err isa CUDAnative.CompilerError
   Evaluated: UndefVarError(:LLVMGetSourceLocation) isa CUDAnative.CompilerError
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:227 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:223 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
generic call: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:229
  Expression: occursin("could not compile codegen_call_nonexisting() for GPU; unsupported LLVM IR", msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:229 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:223 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
generic call: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:230
  Expression: occursin("Reason: unsupported call to the Julia runtime", msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:230 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:223 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
generic call: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:231
  Expression: occursin(#= C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:231 =# @r_str("\\[1\\] codegen_call_nonexisting at .*codegen.jl"), msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:231 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:223 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
compile traces: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:241
  Expression: err isa CUDAnative.CompilerError
   Evaluated: UndefVarError(:LLVMGetSourceLocation) isa CUDAnative.CompilerError
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:241 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:236 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
compile traces: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:243
  Expression: occursin(#= C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:243 =# @r_str("\\[1\\] codegen_call_inner at .*codegen.jl"), msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:243 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:236 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
compile traces: Test Failed at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:244
  Expression: occursin(#= C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:244 =# @r_str("\\[2\\] codegen_call_outer at .*codegen.jl"), msg)
Stacktrace:
 [1] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:244 [inlined]
 [2] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [3] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:236 [inlined]
 [4] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [5] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:209 [inlined]
 [6] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [7] macro expansion at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:153 [inlined]
 [8] macro expansion at C:\Users\sdani\juliastuff\cygwin\home\sdani\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
 [9] top-level scope at C:\Users\sdani\.julia\dev\CUDAnative\test\codegen.jl:5
[ Info: Testing using device GeForce GTX 1060
Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! No docs found for 'CUDAnative.@profile'. [src\lib\profiling.md]
Documenter: building cross-references.
 !! No doc found for reference '[`Base.code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_lowered`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_lowered`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_typed`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_typed`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_warntype`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_warntype`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.getindex`](@ref)'. [src\lib\device\array.md]
Documenter: running document checks.
 > checking for missing docstrings.
 !! 2 docstrings potentially missing:

    CUDAnative.device! :: Tuple{Function,CUDAdrv.CuDevice}
    CUDAnative.device! :: Tuple{CUDAdrv.CuDevice}

 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\device\array.md
Test Summary:                           | Pass  Fail  Broken  Total
CUDAnative                              |  213    11       5    229
  base interface                        |                     No tests
  pointer                               |   20                   20
  code generation                       |   54    11       5     70
    LLVM IR                             |   33             1     34
    PTX assembly                        |   21    11       4     36
      basic reflection                  |    3                    3
      child functions                   |                  1      1
      kernel functions                  |    7             1      8
      IR validation                     |         11             11
        delayed lookup                  |          4              4
        generic call                    |          4              4
        compile traces                  |          3              3
      idempotency                       |                     No tests
      child function reuse              |                  2      2
      child function reuse bis          |                     No tests
      indirect sysimg function use      |    2                    2
      compile for host after PTX        |    1                    1
      LLVM intrinsics                   |                     No tests
      kernel names                      |    8                    8
  code generation (relying on a device) |    2                    2
  execution                             |   28                   28
  pointer (on device)                   |   40                   40
  device arrays                         |   21                   21
  intrinsics                            |   37                   37
  examples                              |    7                    7
  documentation                         |                     No tests
ERROR: LoadError: Some tests did not pass: 213 passed, 11 failed, 0 errored, 5 broken.
in expression starting at C:\Users\sdani\.julia\dev\CUDAnative\test\runtests.jl:7
ERROR: Package CUDAnative errored during testing

```

**Comment by maleadt** [comment]
Julia version too old. Should probably conditionalize that code.

**Comment by SimonDanisch** [comment]
My one? I can update ;)

**Comment by SimonDanisch** [comment]
That looks better:
```
(v0.7) pkg> test CUDAnative
   Testing CUDAnative
 Resolving package versions...
  Updating `C:\Users\sdani\juliastuff\cygwin\tmp\jl_3FB6.tmp\Project.toml`
  [3895d2a7] + CUDAapi v0.4.3
  [e30172f5] + Documenter v0.18.0
  [7a1cc6ca] - FFTW v0.2.2
  [0c68f7d7] - GPUArrays v0.2.4+ [`C:\Users\sdani\.julia\dev\GPUArrays`]
  [295af30f] - Revise v0.3.0
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [44cfe95a] + Pkg
  [9a3f8284] - Random
  [8dfed614] + Test
  Updating `C:\Users\sdani\juliastuff\cygwin\tmp\jl_3FB6.tmp\Manifest.toml`
  [621f4979] - AbstractFFTs v0.3.1
  [9e28174c] - BinDeps v0.8.8
  [864edb3b] - DataStructures v0.8.3
  [ffbed154] + DocStringExtensions v0.4.4
  [e30172f5] + Documenter v0.18.0
  [7a1cc6ca] - FFTW v0.2.2
  [0c68f7d7] - GPUArrays v0.2.4+ [`C:\Users\sdani\.julia\dev\GPUArrays`]
  [189a3867] - Reexport v0.1.0
  [295af30f] - Revise v0.3.0
  [90137ffa] - StaticArrays v0.7.0
  [30578b45] - URIParser v0.3.1
  [7b1f6079] - FileWatching
  [ea8e919c] - SHA
[ Info: Testing using device GeForce GTX 1060


Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! No docs found for 'CUDAnative.@profile'. [src\lib\profiling.md]
Documenter: building cross-references.
 !! No doc found for reference '[`Base.code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_lowered`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_lowered`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_typed`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_typed`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_warntype`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_warntype`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.@code_llvm`](@ref)'. [src\lib\reflection.md]
 !! No doc found for reference '[`Base.getindex`](@ref)'. [src\lib\device\array.md]
Documenter: running document checks.
 > checking for missing docstrings.
 !! 2 docstrings potentially missing:

    CUDAnative.device! :: Tuple{CUDAdrv.CuDevice}
    CUDAnative.device! :: Tuple{Function,CUDAdrv.CuDevice}

 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\reflection.md
 !! Invalid local link: unresolved path
    '@ref' in lib\device\array.md
Test Summary: | Pass  Broken  Total
CUDAnative    |  224       5    229
   Testing CUDAnative tests passed
```

**Pull request merged**
