### PR TITLE
Adjust verifier to new internal ABI

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
The failure on dev is fixed on master https://gitlab.com/JuliaGPU/CUDAnative.jl/-/jobs/221788643

@maleadt are the images built by cron or are you doing it manually?

**Comment by maleadt** [comment]
> @maleadt are the images built by cron or are you doing it manually?

Nightly builds around midnight CET. You can check the image age here: https://hub.docker.com/r/juliagpu/julia/tags. There's also a `versioninfo()` at the start of the build:

```
$ julia -e 'using InteractiveUtils; versioninfo()'
Julia Version 1.3.0-DEV.297
Commit 852d084f3d (2019-05-28 16:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_DEPOT_PATH = /builds/JuliaGPU/CUDAnative.jl/.julia/
```

**Comment by vchuravy** [comment]
bors try

**Pull request merged**
