### PR TITLE
fixed different formatting string for windows in example

### PR DESCRIPTION
**Pull request by floswald**
addresses #190

### CODE REVIEW

**Comment by maleadt** [comment]
Huh, now why did CI skip this. Let me try something.

**Comment by maleadt** [comment]
Seems like that won't work anytime soon. Looks OK, thanks for the contribution!

**Comment by floswald** [comment]
so gitlab doesn't test pull requests? that's, erm...surprising! :-)

**Comment by maleadt** [comment]
Well, we use GitLab to mirror the GitHub repo, do CI/CD over there and push everything back. So I can't blame them for not covering every feature, the missing one being a pull request originating from a foreign repository. Regular PRs work :slightly_smiling_face:

**Pull request merged**
